default:
  callback: "undefined"
  uri:
    $ref: ""
  delay: 300
  payload:
          |
    <!DOCTYPE html>
    <html lang="en">

    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>eKYC</title>
    </head>

     <script> 
              async function submit(e) {
                e.preventDefault();
                let transaction_id = new URLSearchParams(window.location.search).get('transaction_id'), bap_uri = new URLSearchParams(window.location.search).get('bap_uri')

                const data = {context:{transaction_id:transaction_id}}
                try {
                  const response = await fetch("/ondc-seller/form/old/render/submission", {
                    method: "POST",
                    headers: {
                      "Content-Type": "application/json",
                    },
                    body: JSON.stringify(data),
                  });

                  if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                  }

                  const responseData = await response.json();
                  // Handle the response data
                } catch (error) {
                  // Handle errors
                  console.error("Error:", error);
                }
                document.getElementById("textmsg").innerHTML="Form has been submitted successfully"
              }
            </script>

    <body>
      <div id = textmsg>
      <!-- <form action="/ondc-seller/form/submission/ekyc" method="POST"> -->
        <label for="adhrNo">Aadhaar Number </label>
        <input type="text" id="adhrNo" name="adhrNo" />
        <label for="tnc">I agree to fetch the necessary information using my Aadhaar</a></label>
        <input type="checkbox" id="tnc" name="tnc" />
        <input type="hidden" id="formId" name="formId" value=" FO2">
        <input type="submit" onclick="submit(event)" value="Submit" >
     <!-- </form> -->
      </div>
    </body>

    </html>