context:
  transaction_id: '{{transaction_id}}'
  action: 'on_{{method}}'
message:
  ack:
    status: NACK
error:
  code: '20001'
  path: string
  message: Given input does not match any mock input conditions
