flows:        
  - summary: IGM seller flow
    id: igm-flow
    shouldDispaly: true
    version:
      - 2.0.0
      - 2.1.0
    input:
      $ref: ./igm-flow/input.yaml
    calls:
      $ref: ./igm-flow/protocolCalls.yaml
    config_selector:
      $ref: ./igm-flow/selector.yaml