default:
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"

#v 2.0.0 personal loan
personal-loan:
  condition:
      operation:
        type: AND
        input:
          value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.intent.category.descriptor.code"
                  - PERSONAL_LOAN
          - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.context.domain"
                    - "ONDC:FIS12"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - "2.0.0"
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_search.yaml"
