default:
  callback: "on_status"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error_status.yaml"


personal-loan-1:
  condition:
    operation:
      type: EQUAL
      title: Check status message code
      input:
        value:
          - operation:
              type: READ
              input:
                value: "req_body.message.order_id"
          - "ORDER_ID_1_PERSONAL_LOAN"
  callback: "on_status"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_status.yaml"

