default:
  callback: "on_update"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"

#v 2.0.0
personal-loan1_old:
  condition:
    operation:
        type: AND
        input:
          value:
           - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order.id"
                  - "ORDER_ID_1_PERSONAL_LOAN"
           - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - "2.0.0"
  callback: "on_update"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./loan/personal-loan_2_0_0/template/on_update.yaml"


