issue:
  
  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  
  - name: "actor_type"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

  - name: "item_ref_id"
    key: "ref.ITEM"
    type: "text"
    errorText: "item_ref_id is required"
    required: true
    summary: This attribute is item_ref_id.
  
  - name: "provider_ref_id"
    key: "ref.PROVIDER"
    type: "text"

    summary: This attribute is provider_ref_id.

  - name: "fulfillment_ref_id"
    key: "ref.FULFILLMENt"
    type: "text"

    summary: This attribute is fulfillment_ref_id.
  
  - name: "transaction_ref_id"
    key: "ref.TRANSACTION"
    type: "text"

    summary: This attribute is transaction_ref_id.

issue2:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.
  
issue3:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

issue4:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

issue5:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

issue6:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

issue7:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.

issue8:
  - name: "action_id"
    key: "id"
    type: "text"
    defaultValue: "0"

  # OPEN,PROCESSING,INFO_REQUESTED,INFO_PROVIDED, RESOLVED
  - name: "description_code"
    key: "actions_description.code"
    type: "select"
    defaultValue: "OPEN"

    defaultOptions:
      - key: "OPEN"
        value: "OPEN"
      - key: "INFO_REQUESTED"
        value: "INFO_REQUESTED"
      - key: "INFO_PROVIDED"
        value: "INFO_PROVIDED"
      - key: "RESOLVED"
        value: "RESOLVED"
      - key: "PROCESSING"
        value: "PROCESSING"
    errorText: "Please select a field"
    required: true
    summary: This attribute is description_code.

  - name: "short_desc"
    key: "actions_description.short_desc"
    type: "text"
    errorText: "short_desc is required"
    defaultValue: "OPEN"
    required: true
    summary: This attribute is short_desc.
  
  - name: "actor_name"
    key: "actor_detail.name"
    type: "text"
    defaultValue: "Sam Manuel"
    required: false
    summary: This attribute is Actor_Name.