session-builder:
  type: "session-builder"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: true
  config: "session-builder" #name of the call
  nextRequest: "issue"
  preRequest: session-builder
  isCollapsed: false
  current: session-builder

issue_status:
  type: "issue_status"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: true
  config: "issue_status" #name of the call
  nextRequest: "on_issue_status"
  preRequest: session-builder
  isCollapsed: false

on_issue_status:
  type: "on_issue_status"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: false
  config: "on_issue_status" #name of the call
  nextRequest: "issue"
  preRequest: issue_status
  isCollapsed: false
  current: on_issue_status

issue:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue" #name of the call
  nextRequest: "on_issue"
  preRequest: issue
  isCollapsed: false
  current: issue

on_issue:
  type: "on_issue"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: false
  config: "on_issue" #name of the call
  nextRequest: "issue2"
  preRequest: issue
  isCollapsed: false
  current: on_issue
  # default_payload:
  #   $ref: ./default_payload.yaml#/settle

issue2:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue2" #name of the call
  nextRequest: "issue3"
  preRequest: on_issue
  isCollapsed: false
  current: issue2

issue3:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue3" #name of the call
  nextRequest: "issue4"
  preRequest: issue2
  isCollapsed: false
  current: issue3

issue4:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue4" #name of the call
  nextRequest: "issue5"
  preRequest: issue3
  isCollapsed: false
  current: issue4

issue5:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue5" #name of the call
  nextRequest: "issue6"
  preRequest: issue4
  isCollapsed: false
  current: issue5


issue6:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue6" #name of the call
  nextRequest: "issue7"
  preRequest: issue5
  isCollapsed: false
  current: issue6


issue7:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue7" #name of the call
  nextRequest: "issue7"
  preRequest: issue6
  isCollapsed: false
  current: issue7