session-builder:
  type: "session-builder"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: true
  config: "session-builder" #name of the call
  nextRequest: "issue"
  preRequest: session-builder
  isCollapsed: false
  current: session-builder


issue:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue" #name of the call
  nextRequest: "on_issue"
  preRequest: issue
  isCollapsed: false
  current: issue

on_issue:
  type: "on_issue"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: false
  config: "on_issue" #name of the call
  nextRequest: "issue2"
  preRequest: issue
  isCollapsed: false
  current: on_issue
  # default_payload:
  #   $ref: ./default_payload.yaml#/settle

issue2:
  type: "issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: false
  config: "issue2" #name of the call
  nextRequest: "on_issue2"
  preRequest: on_issue
  isCollapsed: false
  current: issue2
  # default_payload:
  #   $ref: ./default_payload.yaml#/settle

on_issue2:
  type: "on_issue"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: false
  config: "on_issue2" #name of the call
  nextRequest: "issue3"
  preRequest: issue
  isCollapsed: false
  current: on_issue2
  # default_payload:

# issue3:
#   type: "issue"
#   category: "sender"
#   target: "NP"
#   executed: false
#   shouldRender: false
#   config: "issue3" #name of the call
#   nextRequest: "on_issue3"
#   preRequest: on_issue2
#   isCollapsed: false
#   current: issue3

# on_issue3:
#   type: "on_issue"
#   category: "reciever"
#   target: "NP"
#   executed: false
#   shouldRender: false
#   config: "on_issue3" #name of the call
#   nextRequest: "issue4"
#   preRequest: issue3
#   isCollapsed: false
#   current: on_issue3