context:
  transaction_id: "{{transaction_id}}"
  action: on_confirm
  timestamp: "{{timestamp}}"
  message_id: "{{message_id}}"

order_id: INTERCITY_ORDER_ID
order_status: ACTIVE

intercity_items:
  - id: INTERCITY_BUS_ITEM_ID
    descriptor:
      name: Seater Ticket
      code: SEAT
    price:
      currency: INR
      value: "800"
    quantity:
      selected:
        count: 1
    fulfillment_ids:
      - F1
    category_ids:
      - C1

payment_id: PAYMENT_ID_1
payment_status: NOT-PAID

trips:
  - id: "F1"
    type: "TRIP"
    stops:
      - id: "S2"
        type: "PICKUP"
        location:
          descriptor:
            name: "Agara"
            code: "std:080-pincode:560034"
          gps: "12.924479, 77.648999"
        time:
          label: "DATE_TIME"
          timestamp: "2023-09-06T06:30:00.000Z"
        authorization:
          type: "QR"
          token: "iVBORw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GIAAAApklEQVR4Xu2UMQ4EMQgD/QP+/0vK6zjsvayUMmavWxQpMAUBkwS12wcveAAkgNSCD3rR5Lkgoai3GUCMgWqbAEYR3HxAkZlzU/0MyBisYRsgI1ERFfcpBpA+ze6k56Cj7KTdXNigFWZvSOpsgqLfd18i2aAukXh9TXBNmdWt5gzA/oqzWkkN8HtA7G8CNOwYAiZt3wZixUfkA32OHNQq7Bxs9oI/gC/9fV8AVCkPjQAAAABJRU5ErkJggg=="
      - id: "S5"
        type: "DROP"
        location:
          descriptor:
            name: "Ameerpet"
            code: "std:040-pincode:500016"
          gps: "17.441586, 78.441581"
        time:
          label: "DATE_TIME"
          timestamp: "2023-09-06T15:10:00.000Z"
    customer:
      person:
        name: "Joe Adams"
        age: "30"
        gender: "MALE"
      contact:
        phone: "+91-9988776655"
    vehicle:
      category: "BUS"
    tags:
      - descriptor:
          code: "SEAT_GRID"
        list:
          - descriptor:
              code: "X"
            value: "0"
          - descriptor:
              code: "Y"
            value: "0"
          - descriptor:
              code: "Z"
            value: "0"
          - descriptor:
              code: "X_SIZE"
            value: "1"
          - descriptor:
              code: "Y_SIZE"
            value: "1"
          - descriptor:
              code: "NUMBER"
            value: "A1"
          - descriptor:
              code: "RESTRICTED_GENDER"
            value: "ANY"
          - descriptor:
              code: "SINGLE_SEAT"
            value: "TRUE"
          - descriptor:
              code: "SEAT_PRICE"
            value: "50"
          - descriptor:
              code: "SELECTED_SEAT"
            value: "A1"
          - descriptor:
              code: "ITEM_ID"
            value: "I1"

price: "949"

breakup:
  - title: BASE_FARE
    price:
      currency: INR
      value: "800"
  - title: CGST @ 5%
    price:
      currency: INR
      value: "40"
  - title: SGST @ 5%
    price:
      currency: INR
      value: "40"
  - title: CONVENIENCE_FEE
    price:
      currency: INR
      value: "19"
  - title: Seat Fare
    price:
      currency: INR
      value: "50"
