context:
  transaction_id: "{{transaction_id}}"
  action: on_search
  timestamp: "{{timestamp}}"
  message_id: "{{message_id}}"

name: ABC Bus Services Solutions
images:
  - url: https://abc-bus.in/logos/logo.ico
trips:
  - id: F1
    type: TRIP
    stops:
      - type: START
        location:
          descriptor:
            name: Bangalore
            code: std:080
          gps: "12.979759, 77.590427"
      - type: PICKUP
        location:
          descriptor:
            name: Agara
            code: std:080-pincode:560034
          gps: "12.924479, 77.648999"
      - type: PICKUP
        location:
          descriptor:
            name: Bellandur
            code: std:080-pincode:560103
          gps: "12.930839, 77.677941"
      - type: END
        location:
          descriptor:
            name: Hyderabad
            code: std:040
          gps: "17.399832, 78.505532"
      - type: DROP
        location:
          descriptor:
            name: Ameerpet
            code: std:040-pincode:500016
          gps: "17.441586, 78.441581"
      - type: DROP
        location:
          descriptor:
            name: Central Bus Station
            code: std:040-pincode:500012
          gps: "17.379024, 78.482443"
    vehicle:
      category: BUS
  - id: F2
    type: TRIP
    stops:
      - type: START
        location:
          descriptor:
            name: Bangalore
            code: std:080
          gps: "12.979759, 77.590427"
      - type: PICKUP
        location:
          descriptor:
            name: Agara
            code: std:080-pincode:560034
          gps: "12.924479, 77.648999"
      - type: PICKUP
        location:
          descriptor:
            name: Bellandur
            code: std:080-pincode:560103
          gps: "12.930839, 77.677941"
      - type: END
        location:
          descriptor:
            name: CHENNAI
            code: std:040
          gps: "17.399832, 78.505532"
      - type: DROP
        location:
          descriptor:
            name: Ameerpet
            code: std:040-pincode:500016
          gps: "17.441586, 78.441581"
      - type: DROP
        location:
          descriptor:
            name: Central Bus Station
            code: std:040-pincode:500012
          gps: "17.379024, 78.482443"
    vehicle:
      category: BUS
