context:
  transaction_id: "{{transaction_id}}"
  action: on_search
  timestamp: "{{timestamp}}"
  message_id: "{{message_id}}"

name: ABC Bus Services Solutions
images:
  - url: https://abc-bus.in/logos/logo.ico

trips:
  - id: F1
    type: TRIP
    stops:
      - id: S1
        type: START
        location:
          descriptor:
            name: Bangalore
            code: std:080
      - id: S2
        type: PICKUP
        location:
          descriptor:
            name: Agara
            code: std:080-pincode:560034
          gps: "12.924479, 77.648999"
        time:
          label: DATE_TIME
          timestamp: "2023-09-06T06:30:00.000Z"
      - id: S3
        type: PICKUP
        location:
          descriptor:
            name: Bellandur
            code: std:080-pincode:560103
          gps: "12.930839, 77.677941"
        time:
          label: DATE_TIME
          timestamp: "2023-09-06T06:45:00.000Z"
      - id: S4
        type: END
        location:
          descriptor:
            name: Hyderabad
            code: std:040
    vehicle:
      category: BUS
    tags:
      - descriptor:
          code: VEHICLE_GRID
        display: false
        list:
          - descriptor:
              code: X_MAX
            value: "14"
          - descriptor:
              code: Y_MAX
            value: "3"
          - descriptor:
              code: Z_MAX
            value: "1"
          - descriptor:
              code: X_LOBBY_START

intercity_items:
  - id: INTERCITY_BUS_ITEM_ID
    descriptor:
      name: Seater Ticket
      code: SEAT
    price:
      currency: INR
      value: "899"
    quantity:
      available:
        count: 1
      maximum:
        count: 1
    fulfillment_ids:
      - F1
    category_ids:
      - C1
  - id: I2
    descriptor:
      name: Sleeper Ticket
      code: SEAT
    price:
      currency: INR
      value: "1899"
    quantity:
      available:
        count: 1
    fulfillment_ids:
      - F1
    category_ids:
      - C2
