default:
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"





get_all_station_codes_metro1:
  condition:
      operation:
        type: AND
        input:
          value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.intent.fulfillment.stops.0.location.gps"
                  - undefined
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.intent.fulfillment.vehicle.category"
                  - METRO
          - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.context.domain"
                    - "ONDC:TRV11"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.location.city.code"
                  - std:011
          - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.context.version"
                    - 2.0.0
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.intent.fulfillment.stops"
                  - undefined
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./metro/template/on_search_station-1.yaml"




