default:
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"

get_bus_service:
  condition:
    operation:
      type: AND
      input:
        value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.domain"
                  - "ONDC:TRV12"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.location.city.code"
                  - std:011
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.version"
                  - 2.0.0
  callback: "on_search"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./intercity/template/on_search_station-3.yaml"
