default:
  callback: "on_status"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./default/template/error.yaml"


metro:
  condition:
      operation:
        type: AND
        input:
          value:
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.message.order_id"
                  - ORDER_ID_1_METRO
          - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.context.domain"
                    - "ONDC:TRV11"
          - operation:
              type: EQUAL
              title: Check search message code
              input:
                value:
                  - operation:
                      type: READ
                      input:
                        value: "req_body.context.location.city.code"
                  - std:011
          - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.context.version"
                    - 2.0.0
  callback: "on_status"
  uri:
    $ref: ""
  delay: 300
  payload:
    $ref: "./metro/template/on_status.yaml"



    