context:
  transaction_id: '{{transaction_id}}'
  action: on_confirm
  timestamp: '{{timestamp}}'
  message_id: '{{message_id}}'

billing_name: John Doe
billing_email: john.doe@example.com
billing_phone: "+91-9897867564" 

order_id: ORDER_ID_1_METRO
order_created_at: "2021-03-23T10:00:40.065Z"
order_updated_at: "2021-03-23T10:00:40.065Z"
order_status: ACTIVE
metro_items:
- id: I1
  category_ids:
  - C1
  descriptor:
    name: Single Journey Ticket
    code: SJT
  price:
    currency: INR
    value: '60'
  quantity:
    selected:
      count: 2
  fulfillment_ids:
  - F1
  - F2
  time:
    label: Validity
    duration: PT2D
trips:
- id: F1
  type: TRIP
  stops:
  - type: START
    location:
      descriptor:
        name: Shaheed Sthal(New Bus Adda)
        code: SHAHEED_STHAL
      gps: 28.686576, 77.441632
    authorization:
      type: QR
      token: iVBORw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GIAAAApklEQVR4Xu2UMQ4EMQgD/QP+/0vK6zjsvayUMmavWxQpMAUBkwS12wcveAAkgNSCD3rR5Lkgoai3GUCMgWqbAEYR3HxAkZlzU/0MyBisYRsgI1ERFfcpBpA+ze6k56Cj7KTdXNigFWZvSOpsgqLfd18i2aAukXh9TXBNmdWt5gzA/oqzWkkN8HtA7G8CNOwYAiZt3wZixUfkA32OHNQq7Bxs9oI/gC/9fV8AVCkPjQAAAABJRU5ErkJggg==
      valid_to: '2021-03-23T23:59:59.999Z'
      status: UNCLAIMED
    id: '1'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 1
    location:
      descriptor:
        name: Hindon River
        code: HINDON_RIVER
      gps: 28.686176, 77.442632
    id: '2'
    parent_stop_id: '1'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 2
    location:
      descriptor:
        name: Arthala
      gps: 28.181276, 77.442332
    id: '3'
    parent_stop_id: '2'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 3
    location:
      descriptor:
        name: Mohan Nagar
      gps: 28.981276, 77.772332
    id: '4'
    parent_stop_id: '3'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 4
    location:
      descriptor:
        name: Shyam Park
      gps: 28.620976, 77.046732
    id: '5'
    parent_stop_id: '4'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 5
    location:
      descriptor:
        name: Major Mohit Sharma Rajendra Nagar
      gps: 28.120976, 77.946732
    id: '6'
    parent_stop_id: '5'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 6
    location:
      descriptor:
        name: Raj Bagh
      gps: 28.677076, 77.346632
    id: '7'
    parent_stop_id: '6'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 7
    location:
      descriptor:
        name: Shaheed Nagar
      gps: 28.617076, 77.146632
    id: '8'
    parent_stop_id: '7'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 8
    location:
      descriptor:
        name: Dilshad Garden
      gps: 28.917076, 77.146632
    id: '9'
    parent_stop_id: '8'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 9
    location:
      descriptor:
        name: Jhilmil
      gps: 28.897076, 77.146632
    id: '10'
    parent_stop_id: '9'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 10
    location:
      descriptor:
        name: Mansarovar Park
      gps: 28.117076, 77.116632
    id: '11'
    parent_stop_id: '10'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 11
    location:
      descriptor:
        name: Shahdara
      gps: 28.127076, 77.416632
    id: '12'
    parent_stop_id: '11'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 12
    location:
      descriptor:
        name: Welcome
      gps: 28.217076, 77.216632
    id: '13'
    parent_stop_id: '12'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 13
    location:
      descriptor:
        name: Seelampur
      gps: 28.327076, 77.416632
    id: '14'
    parent_stop_id: '13'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 14
    location:
      descriptor:
        name: Shastri Park
      gps: 28.427076, 77.446632
    id: '15'
    parent_stop_id: '14'
  - type: TRANSIT_STOP
    instructions:
      name: Stop 15
      short_desc: Please Change here for Yellow Line
    location:
      descriptor:
        name: Kashmere Gate
      gps: 28.738426, 77.139922
    id: '16'
    parent_stop_id: '15'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 16
    location:
      descriptor:
        name: Civil Lines
      gps: 28.627076, 77.646632
    id: '17'
    parent_stop_id: '16'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 17
    location:
      descriptor:
        name: Vidhan Sabha
      gps: 28.727076, 77.746632
    id: '18'
    parent_stop_id: '17'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 18
    location:
      descriptor:
        name: Vishwavidyalaya
      gps: 28.827076, 77.846632
    id: '19'
    parent_stop_id: '18'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 19
    location:
      descriptor:
        name: Guru Tegh Bahadur Nagar
      gps: 28.927076, 77.946632
    id: '20'
    parent_stop_id: '19'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 20
    location:
      descriptor:
        name: Model Town
      gps: 28.217076, 77.496632
    id: '21'
    parent_stop_id: '20'
  - type: END
    location:
      descriptor:
        name: Azadpur
        code: AZADPUR
      gps: 28.707358, 77.180910
    id: '22'
    parent_stop_id: '21'
  vehicle:
    category: METRO
  tags:
  - descriptor:
      code: TICKET_INFO
    display: false
    list:
    - descriptor:
        code: NUMBER
      value: 8ed21b6f
- id: F2
  type: TRIP
  stops:
  - type: START
    location:
      descriptor:
        name: Shaheed Sthal(New Bus Adda)
        code: SHAHEED_STHAL
      gps: 28.686576, 77.441632
    authorization:
      type: QR
      token: xNMPRw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GIAAAApklEQVR4Xu2UMQ4EMQgD/QP+/0vK6zjsvayUMmavWxQpMAUBkwS12wcveAAkgNSCD3rR5Lkgoai3GUCMgWqbAEYR3HxAkZlzU/0MyBisYRsgI1ERFfcpBpA+ze6k56Cj7KTdXNigFWZvSOpsgqLfd18i2aAukXh9TXBNmdWt5gzA/oqzWkkN8HtA7G8CNOwYAiZt3wZixUfkA32OHNQq7Bxs9oI/gC/9fV8AVCkPjQAAAABJRU5ErkJggg==
      valid_to: '2021-03-23T23:59:59.999Z'
      status: UNCLAIMED
    id: '1'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 1
    location:
      descriptor:
        name: Hindon River
        code: HINDON_RIVER
      gps: 28.686176, 77.442632
    id: '2'
    parent_stop_id: '1'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 2
    location:
      descriptor:
        name: Arthala
      gps: 28.181276, 77.442332
    id: '3'
    parent_stop_id: '2'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 3
    location:
      descriptor:
        name: Mohan Nagar
      gps: 28.981276, 77.772332
    id: '4'
    parent_stop_id: '3'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 4
    location:
      descriptor:
        name: Shyam Park
      gps: 28.620976, 77.046732
    id: '5'
    parent_stop_id: '4'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 5
    location:
      descriptor:
        name: Major Mohit Sharma Rajendra Nagar
      gps: 28.120976, 77.946732
    id: '6'
    parent_stop_id: '5'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 6
    location:
      descriptor:
        name: Raj Bagh
      gps: 28.677076, 77.346632
    id: '7'
    parent_stop_id: '6'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 7
    location:
      descriptor:
        name: Shaheed Nagar
      gps: 28.617076, 77.146632
    id: '8'
    parent_stop_id: '7'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 8
    location:
      descriptor:
        name: Dilshad Garden
      gps: 28.917076, 77.146632
    id: '9'
    parent_stop_id: '8'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 9
    location:
      descriptor:
        name: Jhilmil
      gps: 28.897076, 77.146632
    id: '10'
    parent_stop_id: '9'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 10
    location:
      descriptor:
        name: Mansarovar Park
      gps: 28.117076, 77.116632
    id: '11'
    parent_stop_id: '10'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 11
    location:
      descriptor:
        name: Shahdara
      gps: 28.127076, 77.416632
    id: '12'
    parent_stop_id: '11'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 12
    location:
      descriptor:
        name: Welcome
      gps: 28.217076, 77.216632
    id: '13'
    parent_stop_id: '12'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 13
    location:
      descriptor:
        name: Seelampur
      gps: 28.327076, 77.416632
    id: '14'
    parent_stop_id: '13'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 14
    location:
      descriptor:
        name: Shastri Park
      gps: 28.427076, 77.446632
    id: '15'
    parent_stop_id: '14'
  - type: TRANSIT_STOP
    instructions:
      name: Stop 15
      short_desc: Please Change here for Yellow Line
    location:
      descriptor:
        name: Kashmere Gate
      gps: 28.738426, 77.139922
    id: '16'
    parent_stop_id: '15'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 16
    location:
      descriptor:
        name: Civil Lines
      gps: 28.627076, 77.646632
    id: '17'
    parent_stop_id: '16'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 17
    location:
      descriptor:
        name: Vidhan Sabha
      gps: 28.727076, 77.746632
    id: '18'
    parent_stop_id: '17'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 18
    location:
      descriptor:
        name: Vishwavidyalaya
      gps: 28.827076, 77.846632
    id: '19'
    parent_stop_id: '18'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 19
    location:
      descriptor:
        name: Guru Tegh Bahadur Nagar
      gps: 28.927076, 77.946632
    id: '20'
    parent_stop_id: '19'
  - type: INTERMEDIATE_STOP
    instructions:
      name: Stop 20
    location:
      descriptor:
        name: Model Town
      gps: 28.217076, 77.496632
    id: '21'
    parent_stop_id: '20'
  - type: END
    location:
      descriptor:
        name: Azadpur
        code: AZADPUR
      gps: 28.707358, 77.180910
    id: '22'
    parent_stop_id: '21'
  vehicle:
    category: METRO
  tags:
  - descriptor:
      code: TICKET_INFO
    display: false
    list:
    - descriptor:
        code: NUMBER
      value: 7f3a8e9d

breakup:
- title: BASE_FARE
  item:
    id: I1
    price:
      currency: INR
      value: '60'
    quantity:
      selected:
        count: 2
  price:
    currency: INR
    value: '120'
price: '120'
payment_id: PA1
payment_status: PAID
amount: "120"
payment_tags:
  SETTLEMENT_TERMS:
    display: false
    SETTLEMENT_WINDOW: PT30D
    SETTLEMENT_BASIS: INVOICE_RECEIPT
    MANDATORY_ARBITRATION: "TRUE"
    COURT_JURISDICTION: New Delhi
    STATIC_TERMS: "https://api.example-bpp.com/booking/term"
    SETTLEMENT_AMOUNT: "59"

    