context:
  transaction_id: '{{transaction_id}}'
  action: on_init
  timestamp: '{{timestamp}}'
  message_id: '{{message_id}}'
loan_offers: 
- id: "ITEM_ID_PERSONAL_LOAN"
  descriptor: 
    code: "PERSONAL_LOAN"
    name: "Personal Loan"
  price: 
    currency: "INR"
    value: "232800"
  tags: 
  -
    descriptor: 
      code: "LOAN_INFO"
      name: "Loan Information"
    list: 
    -
      descriptor: 
        code: "INTEREST_RATE"
        name: "Interest Rate"
        short_desc: "Loans starting from 12% (p.a)"
      value: "12%"
    -
      descriptor: 
        code: "TERM"
        name: "Loan Term"
        short_desc: "Loans Duration 5 months"
      value: "5 months"
    -
      descriptor: 
        code: "INTEREST_RATE_TYPE"
        name: "Interest rate type"
        short_desc: "Fixed Interest type"
      value: "FIXED"
    -
      descriptor: 
        code: "APPLICATION_FEE"
        name: "Application Fees"
      value: "1000 INR"
    -
      descriptor: 
        code: "FORECLOSURE_FEE"
        name: "Foreclosure Penalty"
        short_desc: "Loan Foreclosure Penalty"
      value: "0.5%"
    -
      descriptor: 
        code: "INTEREST_RATE_CONVERSION_CHARGE"
        name: "interest rate conversion charges"
      value: "1000 INR"
    -
      descriptor: 
        code: "DELAY_PENALTY_FEE"
        name: "Delayed payments penalty"
        short_desc: "Delayed payments penalty"
      value: "5%"
    -
      descriptor: 
        code: "OTHER_PENALTY_FEE"
        name: "Other Penal Charges"
        short_desc: "Other Penal Charges"
      value: "1%"
    -
      descriptor: 
        code: "ANNUAL_PERCENTAGE_RATE"
        name: "Annual Percentage Rate"
        short_desc: "Effective annualized interest rate in percentage computed on net disbursed amount using IRR approach and reducing balance method"
      value: "5%"
    -
      descriptor: 
        code: "REPAYMENT_FREQUENCY"
        name: "Repayment Frequency"
        short_desc: "Repayment Frequency by borrower"
      value: "MONTHLY"
    -
      descriptor: 
        code: "NUMBER_OF_INSTALLMENTS_OF_REPAYMENT"
        name: "Number of installments of repayment"
        short_desc: "Number of installments borrower has to make to payback the loan"
      value: "45"
    -
      descriptor: 
        code: "TNC_LINK"
        name: "Terms & Conditions"
        short_desc: "Terms and Conditions"
      value: "https://icicibank.com/loan/tnc.html"
    -
      descriptor: 
        code: "COOL_OFF_PERIOD"
        name: "cool off period"
        short_desc: "Cooling off/look-up period during which borrower shall not be	TAGS m jayega charged any penalty"
      value: "PT30D"
    -
      descriptor: 
        code: "INSTALLMENT_AMOUNT"
        name: "Installment amount"
        short_desc: "Each installment amount of repayment"
      value: "PT30D"
    display: true
  xinput: 
    head: 
      descriptor: 
        name: "Account Information"
      index: 
        min: 0
        cur: 1
        max: 2
      headings: 
      - "Account Information"
      - "Emandate"
      - "Loan Agreement"
    form: 
      id: "F05"
      mime_type: "application/html"
      url: '{{form_url}}form/old/render?transaction_id={{transaction_id}}'
      resubmit: false
      multiple_sumbissions: false
    required: true

customer:
  name: John Doe
  phone: "+91-9999999999"
  email: john.doe@example.com
  fulfillment_state: INITIATED

payments:
  - type: ON_ORDER
    id: PAYMENT_ID_PERSONAL_LOAN
    status: NOT-PAID
    collected_by: BPP
